/**
 * Copyright (c) 2014-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

 // @Generated by gentest/gentest.rb from gentest/fixtures/YGJustifyContentTest.html

var include = require('./include.js');
include.include('../src/YGEnums.js');
include.include('../src/Yoga.js');

describe('YGJustifyContentTest', () => {

  it('justify_content_row_flex_start', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(20);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(92);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(82);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(72);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_row_flex_end', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
    _YGNodeStyleSetJustifyContent(root, _YGJustifyFlexEnd);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(72);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(82);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(92);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(20);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_row_center', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
    _YGNodeStyleSetJustifyContent(root, _YGJustifyCenter);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(36);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(56);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(56);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(36);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_row_space_between', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
    _YGNodeStyleSetJustifyContent(root, _YGJustifySpaceBetween);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(92);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(92);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_row_space_around', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
    _YGNodeStyleSetJustifyContent(root, _YGJustifySpaceAround);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetWidth(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(12);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(80);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(80);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(12);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(102);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_column_flex_start', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(0);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(10);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(0);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(10);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_column_flex_end', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetJustifyContent(root, _YGJustifyFlexEnd);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(72);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(82);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(92);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(72);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(82);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(92);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_column_center', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetJustifyContent(root, _YGJustifyCenter);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(36);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(56);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(36);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(56);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_column_space_between', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetJustifyContent(root, _YGJustifySpaceBetween);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(92);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(92);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeFreeRecursive(root);
  });

  it('justify_content_column_space_around', () => {
    var root = _YGNodeNew();
    _YGNodeStyleSetJustifyContent(root, _YGJustifySpaceAround);
    _YGNodeStyleSetWidth(root, 102);
    _YGNodeStyleSetHeight(root, 102);

    var root_child0 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child0, 10);
    _YGNodeInsertChild(root, root_child0, 0);

    var root_child1 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child1, 10);
    _YGNodeInsertChild(root, root_child1, 1);

    var root_child2 = _YGNodeNew();
    _YGNodeStyleSetHeight(root_child2, 10);
    _YGNodeInsertChild(root, root_child2, 2);
    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(12);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(80);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

    expect(_YGNodeLayoutGetLeft(root)).toBe(0);
    expect(_YGNodeLayoutGetTop(root)).toBe(0);
    expect(_YGNodeLayoutGetWidth(root)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root)).toBe(102);

    expect(_YGNodeLayoutGetLeft(root_child0)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child0)).toBe(12);
    expect(_YGNodeLayoutGetWidth(root_child0)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child0)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child1)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child1)).toBe(46);
    expect(_YGNodeLayoutGetWidth(root_child1)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child1)).toBe(10);

    expect(_YGNodeLayoutGetLeft(root_child2)).toBe(0);
    expect(_YGNodeLayoutGetTop(root_child2)).toBe(80);
    expect(_YGNodeLayoutGetWidth(root_child2)).toBe(102);
    expect(_YGNodeLayoutGetHeight(root_child2)).toBe(10);

    _YGNodeFreeRecursive(root);
  });

});
