/**
 * Copyright (c) 2014-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

 // @Generated by gentest/gentest.rb from gentest/fixtures/_YGMinMaxDimensionTest.html

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetWidth(root, 100);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetMaxWidth(root_child0, 50);
  _YGNodeStyleSetHeight(root_child0, 10);
  _YGNodeInsertChild(root, root_child0, 0);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(10, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
  _YGNodeStyleSetWidth(root, 100);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child0, 10);
  _YGNodeStyleSetMaxHeight(root_child0, 50);
  _YGNodeInsertChild(root, root_child0, 0);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(90, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(10, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetWidth(root, 100);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child0, 1);
  _YGNodeStyleSetMinHeight(root_child0, 60);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child1 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child1, 1);
  _YGNodeInsertChild(root, root_child1, 1);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
  _YGNodeStyleSetWidth(root, 100);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child0, 1);
  _YGNodeStyleSetMinWidth(root_child0, 60);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child1 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child1, 1);
  _YGNodeInsertChild(root, root_child1, 1);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetJustifyContent(root, _YGJustifyCenter);
  _YGNodeStyleSetWidth(root, 100);
  _YGNodeStyleSetMinHeight(root, 100);
  _YGNodeStyleSetMaxHeight(root, 200);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child0, 60);
  _YGNodeStyleSetHeight(root_child0, 60);
  _YGNodeInsertChild(root, root_child0, 0);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(40, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetAlignItems(root, _YGAlignCenter);
  _YGNodeStyleSetMinWidth(root, 100);
  _YGNodeStyleSetMaxWidth(root, 200);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child0, 60);
  _YGNodeStyleSetHeight(root_child0, 60);
  _YGNodeInsertChild(root, root_child0, 0);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(60, _YGNodeLayoutGetHeight(root_child0));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetJustifyContent(root, _YGJustifyCenter);
  _YGNodeStyleSetMinHeight(root, 100);
  _YGNodeStyleSetMaxHeight(root, 110);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child0, 50);
  _YGNodeStyleSetHeight(root_child0, 50);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child1 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child1, 50);
  _YGNodeStyleSetHeight(root_child1, 50);
  _YGNodeInsertChild(root, root_child1, 1);

  const root_child2 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child2, 50);
  _YGNodeStyleSetHeight(root_child2, 50);
  _YGNodeInsertChild(root, root_child2, 2);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(110, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(-20, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child2));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(110, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(-20, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(30, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child1));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child2));
  ASSERT_FLOAT_EQ(80, _YGNodeLayoutGetTop(root_child2));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child2));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child2));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetWidth(root, 200);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexDirection(root_child0, _YGFlexDirectionRow);
  _YGNodeStyleSetMaxWidth(root_child0, 100);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child0_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child0_child0, 1);
  _YGNodeStyleSetHeight(root_child0_child0, 20);
  _YGNodeInsertChild(root_child0, root_child0_child0, 0);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0_child0));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0_child0));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetWidth(root, 200);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexDirection(root_child0, _YGFlexDirectionRow);
  _YGNodeStyleSetMaxWidth(root_child0, 300);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child0_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child0_child0, 1);
  _YGNodeStyleSetHeight(root_child0_child0, 20);
  _YGNodeInsertChild(root_child0, root_child0_child0, 0);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0_child0));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(20, _YGNodeLayoutGetHeight(root_child0_child0));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetFlexDirection(root, _YGFlexDirectionRow);
  _YGNodeStyleSetMinWidth(root, 100);
  _YGNodeStyleSetHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child0, 1);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child1 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child1, 50);
  _YGNodeInsertChild(root, root_child1, 1);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetMinHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexGrow(root_child0, 1);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child1 = _YGNodeNew();
  _YGNodeStyleSetHeight(root_child1, 50);
  _YGNodeInsertChild(root, root_child1, 1);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetWidth(root, 200);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexDirection(root_child0, _YGFlexDirectionRow);
  _YGNodeStyleSetMaxWidth(root_child0, 100);
  _YGNodeStyleSetHeight(root_child0, 100);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child0_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexShrink(root_child0_child0, 1);
  _YGNodeStyleSetFlexBasis(root_child0_child0, 100);
  _YGNodeInsertChild(root_child0, root_child0_child0, 0);

  const root_child0_child1 = _YGNodeNew();
  _YGNodeStyleSetWidth(root_child0_child1, 50);
  _YGNodeInsertChild(root_child0, root_child0_child1, 1);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0_child1));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(200, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetLeft(root_child0_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0_child1));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetWidth(root_child0_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root_child0_child1));

  _YGNodeFreeRecursive(root);
})();

(function() {
  const root = _YGNodeNew();
  _YGNodeStyleSetWidth(root, 100);
  _YGNodeStyleSetMaxHeight(root, 100);

  const root_child0 = _YGNodeNew();
  _YGNodeStyleSetFlexShrink(root_child0, 1);
  _YGNodeStyleSetFlexBasis(root_child0, 100);
  _YGNodeInsertChild(root, root_child0, 0);

  const root_child1 = _YGNodeNew();
  _YGNodeStyleSetHeight(root_child1, 50);
  _YGNodeInsertChild(root, root_child1, 1);
  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionLTR);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeCalculateLayout(root, _YGUndefined, _YGUndefined, _YGDirectionRTL);

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetHeight(root));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child0));
  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetTop(root_child0));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child0));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child0));

  ASSERT_FLOAT_EQ(0, _YGNodeLayoutGetLeft(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetTop(root_child1));
  ASSERT_FLOAT_EQ(100, _YGNodeLayoutGetWidth(root_child1));
  ASSERT_FLOAT_EQ(50, _YGNodeLayoutGetHeight(root_child1));

  _YGNodeFreeRecursive(root);
})();
