# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:yoga_defs.bzl", "PROGRUARD_ANNOTATIONS_TARGET", "SOLOADER_TARGET", "JSR_305_TARGET")

java_library(
    name = "jni",
    srcs = glob(["**/*.java"]),
    proguard_config = "fbjni.pro",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        PROGRUARD_ANNOTATIONS_TARGET,
        SOLOADER_TARGET,
        JSR_305_TARGET,
    ],
)
