# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "JSR_305_TARGET", "PROGRUARD_ANNOTATIONS_TARGET", "SOLOADER_TARGET", "yoga_java_library")

yoga_java_library(
    name = "jni",
    srcs = glob(["**/*.java"]),
    proguard_config = "fbjni.pro",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        PROGRUARD_ANNOTATIONS_TARGET,
        SOLOADER_TARGET,
        JSR_305_TARGET,
    ],
)
