# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "PROGRUARD_ANNOTATIONS_TARGET", "SOLOADER_TARGET", "JSR_305_TARGET", "java_library")

java_library(
    name = "jni",
    srcs = glob(["**/*.java"]),
    proguard_config = "fbjni.pro",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        PROGRUARD_ANNOTATIONS_TARGET,
        SOLOADER_TARGET,
        JSR_305_TARGET,
    ],
)
