# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:yoga_defs.bzl", "YOGA_ROOTS")

prebuilt_jar(
    name = "junit-jar",
    binary_jar = "junit4.jar",
)

java_library(
    name = "junit",
    exported_deps = [
        ":junit-jar",
    ],
    visibility = YOGA_ROOTS,
)
