# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

csharp_library(
  name = 'csslibnet46',
  dll_name = 'Facebook.CSSLayout.dll',
  framework_ver = 'net46',
  srcs = glob(['**/*.cs']),
)

csharp_library(
  name = 'csslibnet45',
  dll_name = 'Facebook.CSSLayout.dll',
  framework_ver = 'net45',
  srcs = glob(['**/*.cs']),
)
