# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:yoga_defs.bzl", "ANDROID_JAVA_TARGET", "ANDROID_SAMPLE_RES_TARGET", "ANDROID_SUPPORT_TARGET", "APPCOMPAT_TARGET", "ANDROID_SUPPORT_TARGET", "SOLOADER_TARGET")

android_library(
    name = "yoga",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ANDROID_JAVA_TARGET,
        ANDROID_SAMPLE_RES_TARGET,
        ANDROID_SUPPORT_TARGET,
        APPCOMPAT_TARGET,
        SOLOADER_TARGET,
    ],
)
