# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

load("//:yoga_defs.bzl", "ANDROID_JAVA_TARGET", "ANDROID_SAMPLE_RES_TARGET", "ANDROID_SUPPORT_TARGET", "APPCOMPAT_TARGET", "SOLOADER_TARGET", "android_library")

android_library(
    name = "yoga",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ANDROID_JAVA_TARGET,
        ANDROID_SAMPLE_RES_TARGET,
        ANDROID_SUPPORT_TARGET,
        APPCOMPAT_TARGET,
        SOLOADER_TARGET,
    ],
)
