# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "YOGA_ROOTS")

android_prebuilt_aar(
    name = "soloader",
    aar = "soloader-0.5.1.aar",
    visibility = YOGA_ROOTS,
)
