# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:yoga_defs.bzl", "YOGA_ROOTS")

android_prebuilt_aar(
    name = "soloader",
    aar = "soloader-0.1.0.aar",
    visibility = YOGA_ROOTS,
)
