name: Setup JavaScript envirionment

runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install emsdk
      uses: ./.github/actions/install-emsdk

    - name: Install ninja
      uses: sudo apt-get install -y ninja-build

    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
      working-directory: javascript
