# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "YOGA_ROOTS", "yoga_prebuilt_jar")

yoga_prebuilt_jar(
    name = "android-support",
    binary_jar = "android-support-v4.jar",
    visibility = YOGA_ROOTS,
)
