# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "YOGA_ROOTS", "prebuilt_jar")

prebuilt_jar(
    name = "android-support",
    binary_jar = "android-support-v4.jar",
    visibility = YOGA_ROOTS,
)
