# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//yoga_defs.bzl")

prebuilt_cxx_library(
    name = "ndklog",
    exported_platform_linker_flags = [
        (
            "^android.*",
            ["-llog"],
        ),
    ],
    header_only = True,
    visibility = YOGA_ROOTS,
)

cxx_library(
    name = "fbjni",
    srcs = glob(["src/main/cpp/**/*.cpp"]),
    header_namespace = "",
    exported_headers = subdir_glob([("src/main/cpp/include", "**/*.h")]),
    compiler_flags = [
        "-DLOG_TAG=\"libfb\"",
        "-DDISABLE_CPUCAP",
        "-DDISABLE_XPLAT",
        "-DHAVE_POSIX_CLOCKS",
        "-fno-omit-frame-pointer",
        "-fexceptions",
        "-frtti",
        "-Wall",
        "-Werror",
        "-Wno-unused-parameter",
        "-std=c++11",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":ndklog",
        FBJNI_JAVA_TARGET,
        JNI_TARGET,
    ],
)
