use_frameworks!

platform :ios, "13.4"

target 'YogaKitSample' do
  pod 'YogaKit', :path => '../../YogaKit.podspec'
  pod 'Yoga', :path => '../../Yoga.podspec'
  pod 'IGListKit', '~> 4.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
    end
  end
end
