platform :ios, '9.0'
use_frameworks!

targetsArray = ['YogaKitSample', 'YogaKitSampleTests']
targetsArray.each do |t|
  target t do
    pod 'Yoga', :path => '../../Yoga.podspec'
    pod 'YogaKit', :path => '../../YogaKit.podspec'
    pod 'IGListKit', '~> 4.0.0'
  end
end
