# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs('//YOGA_DEFS')

android_aar(
  name = 'android',
  manifest_skeleton = 'AndroidManifest.xml',
  deps = [
    ANDROID_JAVA_TARGET,
    ANDROID_RES_TARGET,
    INFER_ANNOTATIONS_TARGET,
    JAVA_TARGET,
    PROGRUARD_ANNOTATIONS_TARGET,
  ],
  visibility = [
    'PUBLIC',
  ],
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.facebook.yoga.android',
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':android',
)
