# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "ANDROID_JAVA_TARGET", "ANDROID_RES_TARGET", "JAVA_TARGET", "PROGRUARD_ANNOTATIONS_TARGET", "yoga_android_aar", "yoga_android_resource")

yoga_android_aar(
    name = "android",
    manifest_skeleton = "src/main/AndroidManifest.xml",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ANDROID_JAVA_TARGET,
        ANDROID_RES_TARGET,
        JAVA_TARGET,
        PROGRUARD_ANNOTATIONS_TARGET,
    ],
)

yoga_android_resource(
    name = "res",
    package = "com.facebook.yoga.android",
    res = "src/main/res",
    visibility = [
        "PUBLIC",
    ],
)
