# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

include_defs('//YOGA_DEFS')

android_binary(
  name = 'sample',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    ANDROID_SAMPLE_JAVA_TARGET,
    ANDROID_SAMPLE_RES_TARGET,
  ],
)

android_resource(
  name = 'res',
  res = 'res',
  package = 'com.facebook.samples.yoga',
  deps = [
    ANDROID_RES_TARGET,
  ],
  visibility = [
    'PUBLIC',
  ],
)

keystore(
    name='debug_keystore',
    store='debug.keystore',
    properties='debug.keystore.properties',
)

project_config(
  src_target = ':sample',
)
