# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

load("//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:yoga_defs.bzl", "ANDROID_RES_TARGET", "ANDROID_SAMPLE_JAVA_TARGET", "ANDROID_SAMPLE_RES_TARGET", "yoga_android_binary", "yoga_android_resource")

yoga_android_binary(
    name = "sample",
    keystore = ":debug_keystore",
    manifest = "AndroidManifest.xml",
    deps = [
        ANDROID_SAMPLE_JAVA_TARGET,
        ANDROID_SAMPLE_RES_TARGET,
    ],
)

yoga_android_resource(
    name = "res",
    package = "com.facebook.samples.yoga",
    res = "res",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ANDROID_RES_TARGET,
    ],
)

fb_native.keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)
