# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs('//YOGA_DEFS')

android_binary(
  name = 'sample',
  manifest = 'AndroidManifest.xml',
  keystore = ':debug_keystore',
  deps = [
    ANDROID_SAMPLE_JAVA_TARGET,
    ANDROID_SAMPLE_RES_TARGET,
  ],
)

keystore(
    name='debug_keystore',
    store='debug.keystore',
    properties='debug.keystore.properties',
)

project_config(
  src_target = ':sample',
)
