# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "yoga_cxx_library")

yoga_cxx_library(
    name = "jni",
    header_namespace = "",
    exported_headers = [
        "jni.h",
        "real/jni.h",
    ],
    force_static = True,
    preprocessor_flags = ["-fmacro-backtrace-limit=0"],
    visibility = ["PUBLIC"],
)
