# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "cxx_library")

cxx_library(
    name = "jni",
    header_namespace = "",
    exported_headers = [
        "jni.h",
        "real/jni.h",
    ],
    force_static = True,
    visibility = ["PUBLIC"],
)
