name: Setup Android envirionment

runs:
  using: "composite"
  steps:
    - name: Select Java Version
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Install NDK 21
      shell: bash
      run: echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;21.3.6528147"
