# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs('//CSSLAYOUT_DEFS')

java_library(
  name = 'annotations',
  srcs = glob(['*.java']),
  source = '1.7',
  target = '1.7',
  deps = [],
  visibility = [CSSLAYOUT_ROOT],
)
