# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "ANDROID_RES_TARGET", "INFER_ANNOTATIONS_TARGET", "JAVA_TARGET", "JSR_305_TARGET", "SOLOADER_TARGET", "android_library")

android_library(
    name = "android",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ANDROID_RES_TARGET,
        INFER_ANNOTATIONS_TARGET,
        JAVA_TARGET,
        JSR_305_TARGET,
        SOLOADER_TARGET,
    ],
)
