# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "ANDROID_RES_TARGET", "INFER_ANNOTATIONS_TARGET", "JAVA_TARGET", "JSR_305_TARGET", "SOLOADER_TARGET", "yoga_android_library")

yoga_android_library(
    name = "android",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ANDROID_RES_TARGET,
        INFER_ANNOTATIONS_TARGET,
        JAVA_TARGET,
        JSR_305_TARGET,
        SOLOADER_TARGET,
    ],
)
