.\Facebook.Yoga.AnyCPU.App\bin\Debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.AnyCPU.App\bin\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.AnyCPU.App\bin\x86\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.AnyCPU.App\bin\x86\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.AnyCPU.App\bin\x64\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.AnyCPU.App\bin\x64\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.AnyCPU32Bit.App\bin\Debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.AnyCPU32Bit.App\bin\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.AnyCPU32Bit.App\bin\x86\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.AnyCPU32Bit.App\bin\x86\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.AnyCPU32Bit.App\bin\x64\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.AnyCPU32Bit.App\bin\x64\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.NET451.App\bin\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.NET451.App\bin\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.NET451.App\bin\x86\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.NET451.App\bin\x86\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.NET451.App\bin\x64\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.NET451.App\bin\x64\release\Facebook.Yoga.App.exe

.\Facebook.Yoga.NET461.App\bin\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.NET461.App\bin\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.NET461.App\bin\x86\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.NET461.App\bin\x86\release\Facebook.Yoga.App.exe
 \
.\Facebook.Yoga.NET461.App\bin\x64\debug\Facebook.Yoga.App.exe
.\Facebook.Yoga.NET461.App\bin\x64\release\Facebook.Yoga.App.exe

pause