#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Facebook.Yoga.Android.Tests.Resource", IsApplication=true)]

namespace Facebook.Yoga.Android.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Facebook.Yoga.Android.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Facebook.Yoga.Android.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Facebook.Yoga.Android.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Facebook.Yoga.Android.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Facebook.Yoga.Android.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Facebook.Yoga.Android.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Facebook.Yoga.Android.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Facebook.Yoga.Android.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Facebook.Yoga.Android.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Facebook.Yoga.Android.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Facebook.Yoga.Android.Tests.Resource.Layout.test_suite;
			global::Facebook.Yoga.Android.Resource.String.library_name = global::Facebook.Yoga.Android.Tests.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int OptionHostName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int OptionPort = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int OptionRemoteServer = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int OptionsButton = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int ResultFullName = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int ResultMessage = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int ResultResultState = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int ResultRunSingleMethodTest = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int ResultStackTrace = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int ResultsFailed = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ResultsId = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ResultsIgnored = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ResultsInconclusive = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ResultsMessage = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int ResultsPassed = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ResultsResult = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int RunTestsButton = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int TestSuiteListView = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
