"""
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by gentest/gentest.rb from gentest/fixtures/YGPercentageTest.html
"""
import pytest
import yoga


def test_percentage_width_height():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_width_percent(30)
    root_child0.set_height_percent(30)
    root.insert_child(root_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 60
    assert root_child0.get_computed_height() == 60

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 140
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 60
    assert root_child0.get_computed_height() == 60


def test_percentage_position_left_top():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(400)
    root.set_height(400)

    root_child0 = yoga.Node(config)
    root_child0.set_position_percent(yoga.EDGE_LEFT, 10)
    root_child0.set_position_percent(yoga.EDGE_TOP, 20)
    root_child0.set_width_percent(45)
    root_child0.set_height_percent(55)
    root.insert_child(root_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 400
    assert root.get_computed_height() == 400

    assert root_child0.get_computed_left() == 40
    assert root_child0.get_computed_top() == 80
    assert root_child0.get_computed_width() == 180
    assert root_child0.get_computed_height() == 220

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 400
    assert root.get_computed_height() == 400

    assert root_child0.get_computed_left() == 260
    assert root_child0.get_computed_top() == 80
    assert root_child0.get_computed_width() == 180
    assert root_child0.get_computed_height() == 220


def test_percentage_position_bottom_right():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(500)
    root.set_height(500)

    root_child0 = yoga.Node(config)
    root_child0.set_position_percent(yoga.EDGE_RIGHT, 20)
    root_child0.set_position_percent(yoga.EDGE_BOTTOM, 10)
    root_child0.set_width_percent(55)
    root_child0.set_height_percent(15)
    root.insert_child(root_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 500
    assert root.get_computed_height() == 500

    assert root_child0.get_computed_left() == -100
    assert root_child0.get_computed_top() == -50
    assert root_child0.get_computed_width() == 275
    assert root_child0.get_computed_height() == 75

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 500
    assert root.get_computed_height() == 500

    assert root_child0.get_computed_left() == 125
    assert root_child0.get_computed_top() == -50
    assert root_child0.get_computed_width() == 275
    assert root_child0.get_computed_height() == 75


def test_percentage_flex_basis():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(50)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(1)
    root_child1.set_flex_basis_percent(25)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 125
    assert root_child0.get_computed_height() == 200

    assert root_child1.get_computed_left() == 125
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 75
    assert root_child1.get_computed_height() == 200

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 75
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 125
    assert root_child0.get_computed_height() == 200

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 75
    assert root_child1.get_computed_height() == 200


def test_percentage_flex_basis_cross():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(50)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(1)
    root_child1.set_flex_basis_percent(25)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 125

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 125
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 75

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 125

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 125
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 75


def test_percentage_flex_basis_main_max_height():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(10)
    root_child0.set_max_height_percent(60)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(10)
    root_child1.set_max_height_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 52
    assert root_child0.get_computed_height() == 120

    assert root_child1.get_computed_left() == 52
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 148
    assert root_child1.get_computed_height() == 40

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 148
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 52
    assert root_child0.get_computed_height() == 120

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 148
    assert root_child1.get_computed_height() == 40


def test_percentage_flex_basis_cross_max_height():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(10)
    root_child0.set_max_height_percent(60)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(10)
    root_child1.set_max_height_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 120

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 120
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 40

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 120

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 120
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 40


def test_percentage_flex_basis_main_max_width():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(15)
    root_child0.set_max_width_percent(60)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(10)
    root_child1.set_max_width_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 120
    assert root_child0.get_computed_height() == 200

    assert root_child1.get_computed_left() == 120
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 40
    assert root_child1.get_computed_height() == 200

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 80
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 120
    assert root_child0.get_computed_height() == 200

    assert root_child1.get_computed_left() == 40
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 40
    assert root_child1.get_computed_height() == 200


def test_percentage_flex_basis_cross_max_width():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(10)
    root_child0.set_max_width_percent(60)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(15)
    root_child1.set_max_width_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 120
    assert root_child0.get_computed_height() == 50

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 50
    assert root_child1.get_computed_width() == 40
    assert root_child1.get_computed_height() == 150

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 80
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 120
    assert root_child0.get_computed_height() == 50

    assert root_child1.get_computed_left() == 160
    assert root_child1.get_computed_top() == 50
    assert root_child1.get_computed_width() == 40
    assert root_child1.get_computed_height() == 150


def test_percentage_flex_basis_main_min_width():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(15)
    root_child0.set_min_width_percent(60)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(10)
    root_child1.set_min_width_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 120
    assert root_child0.get_computed_height() == 200

    assert root_child1.get_computed_left() == 120
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 80
    assert root_child1.get_computed_height() == 200

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 80
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 120
    assert root_child0.get_computed_height() == 200

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 80
    assert root_child1.get_computed_height() == 200


def test_percentage_flex_basis_cross_min_width():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(10)
    root_child0.set_min_width_percent(60)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(15)
    root_child1.set_min_width_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 50

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 50
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 150

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 50

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 50
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 150


def test_percentage_multiple_nested_with_padding_margin_and_percentage_values():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_flex_basis_percent(10)
    root_child0.set_margin(yoga.EDGE_LEFT, 5)
    root_child0.set_margin(yoga.EDGE_TOP, 5)
    root_child0.set_margin(yoga.EDGE_RIGHT, 5)
    root_child0.set_margin(yoga.EDGE_BOTTOM, 5)
    root_child0.set_padding(yoga.EDGE_LEFT, 3)
    root_child0.set_padding(yoga.EDGE_TOP, 3)
    root_child0.set_padding(yoga.EDGE_RIGHT, 3)
    root_child0.set_padding(yoga.EDGE_BOTTOM, 3)
    root_child0.set_min_width_percent(60)
    root.insert_child(root_child0, 0)

    root_child0_child0 = yoga.Node(config)
    root_child0_child0.set_margin(yoga.EDGE_LEFT, 5)
    root_child0_child0.set_margin(yoga.EDGE_TOP, 5)
    root_child0_child0.set_margin(yoga.EDGE_RIGHT, 5)
    root_child0_child0.set_margin(yoga.EDGE_BOTTOM, 5)
    root_child0_child0.set_padding_percent(yoga.EDGE_LEFT, 3)
    root_child0_child0.set_padding_percent(yoga.EDGE_TOP, 3)
    root_child0_child0.set_padding_percent(yoga.EDGE_RIGHT, 3)
    root_child0_child0.set_padding_percent(yoga.EDGE_BOTTOM, 3)
    root_child0_child0.set_width_percent(50)
    root_child0.insert_child(root_child0_child0, 0)

    root_child0_child0_child0 = yoga.Node(config)
    root_child0_child0_child0.set_margin_percent(yoga.EDGE_LEFT, 5)
    root_child0_child0_child0.set_margin_percent(yoga.EDGE_TOP, 5)
    root_child0_child0_child0.set_margin_percent(yoga.EDGE_RIGHT, 5)
    root_child0_child0_child0.set_margin_percent(yoga.EDGE_BOTTOM, 5)
    root_child0_child0_child0.set_padding(yoga.EDGE_LEFT, 3)
    root_child0_child0_child0.set_padding(yoga.EDGE_TOP, 3)
    root_child0_child0_child0.set_padding(yoga.EDGE_RIGHT, 3)
    root_child0_child0_child0.set_padding(yoga.EDGE_BOTTOM, 3)
    root_child0_child0_child0.set_width_percent(45)
    root_child0_child0.insert_child(root_child0_child0_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(4)
    root_child1.set_flex_basis_percent(15)
    root_child1.set_min_width_percent(20)
    root.insert_child(root_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 5
    assert root_child0.get_computed_top() == 5
    assert root_child0.get_computed_width() == 190
    assert root_child0.get_computed_height() == 48

    assert root_child0_child0.get_computed_left() == 8
    assert root_child0_child0.get_computed_top() == 8
    assert root_child0_child0.get_computed_width() == 92
    assert root_child0_child0.get_computed_height() == 25

    assert root_child0_child0_child0.get_computed_left() == 10
    assert root_child0_child0_child0.get_computed_top() == 10
    assert root_child0_child0_child0.get_computed_width() == 36
    assert root_child0_child0_child0.get_computed_height() == 6

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 58
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 142

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 5
    assert root_child0.get_computed_top() == 5
    assert root_child0.get_computed_width() == 190
    assert root_child0.get_computed_height() == 48

    assert root_child0_child0.get_computed_left() == 90
    assert root_child0_child0.get_computed_top() == 8
    assert root_child0_child0.get_computed_width() == 92
    assert root_child0_child0.get_computed_height() == 25

    assert root_child0_child0_child0.get_computed_left() == 46
    assert root_child0_child0_child0.get_computed_top() == 10
    assert root_child0_child0_child0.get_computed_width() == 36
    assert root_child0_child0_child0.get_computed_height() == 6

    assert root_child1.get_computed_left() == 0
    assert root_child1.get_computed_top() == 58
    assert root_child1.get_computed_width() == 200
    assert root_child1.get_computed_height() == 142


def test_percentage_margin_should_calculate_based_only_on_width():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(100)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_margin_percent(yoga.EDGE_LEFT, 10)
    root_child0.set_margin_percent(yoga.EDGE_TOP, 10)
    root_child0.set_margin_percent(yoga.EDGE_RIGHT, 10)
    root_child0.set_margin_percent(yoga.EDGE_BOTTOM, 10)
    root.insert_child(root_child0, 0)

    root_child0_child0 = yoga.Node(config)
    root_child0_child0.set_width(10)
    root_child0_child0.set_height(10)
    root_child0.insert_child(root_child0_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 20
    assert root_child0.get_computed_top() == 20
    assert root_child0.get_computed_width() == 160
    assert root_child0.get_computed_height() == 60

    assert root_child0_child0.get_computed_left() == 0
    assert root_child0_child0.get_computed_top() == 0
    assert root_child0_child0.get_computed_width() == 10
    assert root_child0_child0.get_computed_height() == 10

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 20
    assert root_child0.get_computed_top() == 20
    assert root_child0.get_computed_width() == 160
    assert root_child0.get_computed_height() == 60

    assert root_child0_child0.get_computed_left() == 150
    assert root_child0_child0.get_computed_top() == 0
    assert root_child0_child0.get_computed_width() == 10
    assert root_child0_child0.get_computed_height() == 10


def test_percentage_padding_should_calculate_based_only_on_width():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(100)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_grow(1)
    root_child0.set_padding_percent(yoga.EDGE_LEFT, 10)
    root_child0.set_padding_percent(yoga.EDGE_TOP, 10)
    root_child0.set_padding_percent(yoga.EDGE_RIGHT, 10)
    root_child0.set_padding_percent(yoga.EDGE_BOTTOM, 10)
    root.insert_child(root_child0, 0)

    root_child0_child0 = yoga.Node(config)
    root_child0_child0.set_width(10)
    root_child0_child0.set_height(10)
    root_child0.insert_child(root_child0_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 100

    assert root_child0_child0.get_computed_left() == 20
    assert root_child0_child0.get_computed_top() == 20
    assert root_child0_child0.get_computed_width() == 10
    assert root_child0_child0.get_computed_height() == 10

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 200
    assert root_child0.get_computed_height() == 100

    assert root_child0_child0.get_computed_left() == 170
    assert root_child0_child0.get_computed_top() == 20
    assert root_child0_child0.get_computed_width() == 10
    assert root_child0_child0.get_computed_height() == 10


def test_percentage_absolute_position():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(200)
    root.set_height(100)

    root_child0 = yoga.Node(config)
    root_child0.set_position_type(yoga.POSITION_TYPE_ABSOLUTE)
    root_child0.set_position_percent(yoga.EDGE_LEFT, 30)
    root_child0.set_position_percent(yoga.EDGE_TOP, 10)
    root_child0.set_width(10)
    root_child0.set_height(10)
    root.insert_child(root_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 60
    assert root_child0.get_computed_top() == 10
    assert root_child0.get_computed_width() == 10
    assert root_child0.get_computed_height() == 10

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 60
    assert root_child0.get_computed_top() == 10
    assert root_child0.get_computed_width() == 10
    assert root_child0.get_computed_height() == 10


def test_percentage_width_height_undefined_parent_size():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)

    root_child0 = yoga.Node(config)
    root_child0.set_width_percent(50)
    root_child0.set_height_percent(50)
    root.insert_child(root_child0, 0)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 0
    assert root.get_computed_height() == 0

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 0
    assert root_child0.get_computed_height() == 0

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 0
    assert root.get_computed_height() == 0

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 0
    assert root_child0.get_computed_height() == 0


def test_percent_within_flex_grow():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root.set_width(350)
    root.set_height(100)

    root_child0 = yoga.Node(config)
    root_child0.set_width(100)
    root.insert_child(root_child0, 0)

    root_child1 = yoga.Node(config)
    root_child1.set_flex_grow(1)
    root.insert_child(root_child1, 1)

    root_child1_child0 = yoga.Node(config)
    root_child1_child0.set_width_percent(100)
    root_child1.insert_child(root_child1_child0, 0)

    root_child2 = yoga.Node(config)
    root_child2.set_width(100)
    root.insert_child(root_child2, 2)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 350
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 0
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 100
    assert root_child0.get_computed_height() == 100

    assert root_child1.get_computed_left() == 100
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 150
    assert root_child1.get_computed_height() == 100

    assert root_child1_child0.get_computed_left() == 0
    assert root_child1_child0.get_computed_top() == 0
    assert root_child1_child0.get_computed_width() == 150
    assert root_child1_child0.get_computed_height() == 0

    assert root_child2.get_computed_left() == 250
    assert root_child2.get_computed_top() == 0
    assert root_child2.get_computed_width() == 100
    assert root_child2.get_computed_height() == 100

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 350
    assert root.get_computed_height() == 100

    assert root_child0.get_computed_left() == 250
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 100
    assert root_child0.get_computed_height() == 100

    assert root_child1.get_computed_left() == 100
    assert root_child1.get_computed_top() == 0
    assert root_child1.get_computed_width() == 150
    assert root_child1.get_computed_height() == 100

    assert root_child1_child0.get_computed_left() == 0
    assert root_child1_child0.get_computed_top() == 0
    assert root_child1_child0.get_computed_width() == 150
    assert root_child1_child0.get_computed_height() == 0

    assert root_child2.get_computed_left() == 0
    assert root_child2.get_computed_top() == 0
    assert root_child2.get_computed_width() == 100
    assert root_child2.get_computed_height() == 100


def test_percentage_container_in_wrapping_container():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_justify_content(yoga.JUSTIFY_CENTER)
    root.set_align_items(yoga.ALIGN_CENTER)
    root.set_width(200)
    root.set_height(200)

    root_child0 = yoga.Node(config)
    root.insert_child(root_child0, 0)

    root_child0_child0 = yoga.Node(config)
    root_child0_child0.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root_child0_child0.set_justify_content(yoga.JUSTIFY_CENTER)
    root_child0_child0.set_width_percent(100)
    root_child0.insert_child(root_child0_child0, 0)

    root_child0_child0_child0 = yoga.Node(config)
    root_child0_child0_child0.set_width(50)
    root_child0_child0_child0.set_height(50)
    root_child0_child0.insert_child(root_child0_child0_child0, 0)

    root_child0_child0_child1 = yoga.Node(config)
    root_child0_child0_child1.set_width(50)
    root_child0_child0_child1.set_height(50)
    root_child0_child0.insert_child(root_child0_child0_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 50
    assert root_child0.get_computed_top() == 75
    assert root_child0.get_computed_width() == 100
    assert root_child0.get_computed_height() == 50

    assert root_child0_child0.get_computed_left() == 0
    assert root_child0_child0.get_computed_top() == 0
    assert root_child0_child0.get_computed_width() == 100
    assert root_child0_child0.get_computed_height() == 50

    assert root_child0_child0_child0.get_computed_left() == 0
    assert root_child0_child0_child0.get_computed_top() == 0
    assert root_child0_child0_child0.get_computed_width() == 50
    assert root_child0_child0_child0.get_computed_height() == 50

    assert root_child0_child0_child1.get_computed_left() == 50
    assert root_child0_child0_child1.get_computed_top() == 0
    assert root_child0_child0_child1.get_computed_width() == 50
    assert root_child0_child0_child1.get_computed_height() == 50

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 200
    assert root.get_computed_height() == 200

    assert root_child0.get_computed_left() == 50
    assert root_child0.get_computed_top() == 75
    assert root_child0.get_computed_width() == 100
    assert root_child0.get_computed_height() == 50

    assert root_child0_child0.get_computed_left() == 0
    assert root_child0_child0.get_computed_top() == 0
    assert root_child0_child0.get_computed_width() == 100
    assert root_child0_child0.get_computed_height() == 50

    assert root_child0_child0_child0.get_computed_left() == 50
    assert root_child0_child0_child0.get_computed_top() == 0
    assert root_child0_child0_child0.get_computed_width() == 50
    assert root_child0_child0_child0.get_computed_height() == 50

    assert root_child0_child0_child1.get_computed_left() == 0
    assert root_child0_child0_child1.get_computed_top() == 0
    assert root_child0_child0_child1.get_computed_width() == 50
    assert root_child0_child0_child1.get_computed_height() == 50


def test_percent_absolute_position():
    config = yoga.Config()

    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_ABSOLUTE_PERCENTAGE_AGAINST_PADDING_EDGE, True)
    config.set_experimental_feature_enabled(yoga.EXPERIMENTAL_FEATURE_FIX_ABSOLUTE_TRAILING_COLUMN_MARGIN, True)

    root = yoga.Node(config)
    root.set_width(60)
    root.set_height(50)

    root_child0 = yoga.Node(config)
    root_child0.set_flex_direction(yoga.FLEX_DIRECTION_ROW)
    root_child0.set_position_type(yoga.POSITION_TYPE_ABSOLUTE)
    root_child0.set_position_percent(yoga.EDGE_LEFT, 50)
    root_child0.set_width_percent(100)
    root_child0.set_height(50)
    root.insert_child(root_child0, 0)

    root_child0_child0 = yoga.Node(config)
    root_child0_child0.set_width_percent(100)
    root_child0.insert_child(root_child0_child0, 0)

    root_child0_child1 = yoga.Node(config)
    root_child0_child1.set_width_percent(100)
    root_child0.insert_child(root_child0_child1, 1)
    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_LTR);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 60
    assert root.get_computed_height() == 50

    assert root_child0.get_computed_left() == 30
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 60
    assert root_child0.get_computed_height() == 50

    assert root_child0_child0.get_computed_left() == 0
    assert root_child0_child0.get_computed_top() == 0
    assert root_child0_child0.get_computed_width() == 60
    assert root_child0_child0.get_computed_height() == 50

    assert root_child0_child1.get_computed_left() == 60
    assert root_child0_child1.get_computed_top() == 0
    assert root_child0_child1.get_computed_width() == 60
    assert root_child0_child1.get_computed_height() == 50

    root.calculate_layout(float("nan"), float("nan"), yoga.DIRECTION_RTL);

    assert root.get_computed_left() == 0
    assert root.get_computed_top() == 0
    assert root.get_computed_width() == 60
    assert root.get_computed_height() == 50

    assert root_child0.get_computed_left() == 30
    assert root_child0.get_computed_top() == 0
    assert root_child0.get_computed_width() == 60
    assert root_child0.get_computed_height() == 50

    assert root_child0_child0.get_computed_left() == 0
    assert root_child0_child0.get_computed_top() == 0
    assert root_child0_child0.get_computed_width() == 60
    assert root_child0_child0.get_computed_height() == 50

    assert root_child0_child1.get_computed_left() == -60
    assert root_child0_child1.get_computed_top() == 0
    assert root_child0_child1.get_computed_width() == 60
    assert root_child0_child1.get_computed_height() == 50

