# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
load("//:yoga_defs.bzl", "YOGA_ROOTS", "subdir_glob", "yoga_cxx_library")

COMPILER_FLAGS = [
    "-std=c++11",
    "-Wno-missing-prototypes",
]

yoga_cxx_library(
    name = "gtest",
    srcs = glob(["googletest/googletest/src/*.cc"]),
    header_namespace = "",
    exported_headers = subdir_glob([
        ("googletest/googletest/include", "**/*.h"),
        ("googletest/googletest", "src/*.h"),
        ("googletest/googletest", "src/*.cc"),
    ]),
    compiler_flags = COMPILER_FLAGS,
    visibility = YOGA_ROOTS,
    deps = [],
)
