# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:yoga_defs.bzl", "YOGA_ROOTS", "subdir_glob", "yoga_cxx_library", "yoga_prebuilt_cxx_library")

COMPILER_FLAGS = [
    "-std=c++14",
    "-Wno-missing-prototypes",
]

yoga_prebuilt_cxx_library(
    name = "pthread",
    exported_linker_flags = [
        "-lpthread",
    ],
    header_only = True,
)

yoga_cxx_library(
    name = "gtest",
    srcs = glob(["googletest/googletest/src/*.cc"]),
    header_namespace = "",
    exported_headers = subdir_glob([
        ("googletest/googletest/include", "**/*.h"),
        ("googletest/googletest", "src/*.h"),
        ("googletest/googletest", "src/*.cc"),
    ]),
    compiler_flags = COMPILER_FLAGS,
    visibility = YOGA_ROOTS,
    deps = [
        ":pthread",
    ],
)
