# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "yoga_java_library")

yoga_java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    source = "1.7",
    target = "1.7",
    visibility = ["PUBLIC"],
    deps = [],
)
