# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "YOGA_ROOTS", "java_library")

java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    source = "1.7",
    target = "1.7",
    visibility = YOGA_ROOTS,
    deps = [],
)
