name: Python

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: black --check
        uses: ./.github/actions/black
        with:
          directory: ${{ github.workspace }}
