name: CSharp

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-cs

      - name: dotnet test Facebook.Yoga.Tests
        run: dotnet test
        working-directory: csharp/tests/Facebook.Yoga.Tests

  build:
    name: Build and Package [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-cs

      - name: dotnet pack
        run: dotnet pack -c Release
        working-directory: csharp

  build-native:
    name: Build Native Components [${{ matrix.os }}][${{ matrix.rid }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-cs

      - name: Build Native Components
        run: dotnet build -c Release -r ${{ matrix.rid }}
        working-directory: csharp/Yoga

