# Copyright (c) 2014-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//:yoga_defs.bzl", "YOGA_ROOTS", "yoga_java_library", "yoga_prebuilt_jar")

yoga_prebuilt_jar(
    name = "infer-annotations-jar",
    binary_jar = "infer-annotations-1.4.jar",
)

yoga_java_library(
    name = "infer-annotations",
    exported_deps = [
        ":infer-annotations-jar",
    ],
    visibility = YOGA_ROOTS,
)
