# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:yoga_defs.bzl", "YOGA_ROOTS", "yoga_java_library", "yoga_prebuilt_jar")

yoga_prebuilt_jar(
    name = "infer-annotations-jar",
    binary_jar = "infer-annotations-1.4.jar",
)

yoga_java_library(
    name = "infer-annotations",
    visibility = YOGA_ROOTS,
    exported_deps = [
        ":infer-annotations-jar",
    ],
)
